[package]
name = "stm32f103xx-usb"
version = "0.1.0"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]

[dependencies]
bare-metal = "0.2.3"
cortex-m = "0.5.4"
stm32f103xx = "0.10.0"
# TODO: this fork is used temporarily to be able to set USB clocks correctly in the examples
stm32f103xx-hal = { git = "https://github.com/mvirkkunen/stm32f103xx-hal", rev = "71b5d90972abfcf66cd2fe4a9d4e28df2564abfb" }
vcell = "0.1.0"
usb-device = { git = "https://github.com/mvirkkunen/usb-device", rev = "6b70c5906d9c87bf3aaa98e9042f9a7ae7cd8f6b" }

[dev-dependencies]
cortex-m-rt = "0.5.2"
panic-semihosting = "0.3.0"
